### ISSUE TITLE
VS Note

### ISSUE THREAD

**Issue by kolaczyn** [OnlyBens/vscode-extension-ideas#15]
## VS Note

App allowing you to easily organize your notes in VS Code.

### Proposed features:
- Notes can have links to other notes.
- Todo thingy,
- You can convert the notes into a wiki page,
- You can write many code snippets, written in different languages in a single file. You tell which language you're using to get syntax highlighting. Example:
```
{{{js
console.log('Hello World') // I have syntax highlighting for JS
}}}

{{{ts
const helloWorld: string = 'Hello World'; // I have syntax highlighting for TS
console.log(helloWorld);
}}}
```  
The whole idea is inspired by [VimWiki](https://github.com/vimwiki/vimwiki)

**Comment by LuukFTF** [comment]
more ideas: 
- notes are in markdown
- an corresponding mobile app to take notes and edit/look at them (in markdown and normal editting modes)
- notes are stored in repos, so you can create repos with only notes in them
- for the convert notes in wikipages: you could take inspiration from docfx (maybe extend the markdown that it can be used in a filestructure)

**Comment by sereneinserenade** [comment]
one more thing to it: 
integration with https://boostnote.io/

**Comment by tejasag** [comment]
:0 Cool idea!
