### ISSUE TITLE
a real Dracula theme extension

### ISSUE THREAD

**Issue by ayoub3bidi** [OnlyBens/vscode-extension-ideas#50]
The Dracula theme is not really efficient, we need more darkness

**Comment by anirudh242** [comment]
I don't think it'd be fun to watch Ben make a theme

**Comment by ayoub3bidi** [comment]
I totally forgot about this one. I actually found a good theme that I am using for a year now called [Karma](https://marketplace.visualstudio.com/items?itemName=SreetamD.karma) you should try it.
